# -*- coding: utf-8 -*-
"""Bresenham.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3tDqHSpl4h50EYzaS_XRbklLbjltiXM
"""

import matplotlib.pyplot as plt

# Fungsi untuk menghitung titik-titik yang dilewati garis dari (x1, y1) ke (x2, y2)
def simple_line(x1, y1, x2, y2):
    points = []  # Menyimpan titik-titik (x, y) yang membentuk garis

    dx = x2 - x1  # Selisih di sumbu x
    dy = y2 - y1  # Selisih di sumbu y

    # Jika garis lebih mendekati horizontal (selisih x lebih besar daripada selisih y)
    if abs(dx) > abs(dy):
        # Tukar titik jika x1 lebih besar dari x2 agar perhitungan selalu dari kiri ke kanan
        if x1 > x2:
            x1, x2, y1, y2 = x2, x1, y2, y1  # Tukar nilai x1 dengan x2 dan y1 dengan y2

        # Loop dari x1 ke x2 untuk menghitung nilai y
        for x in range(x1, x2 + 1):
            y = y1 + dy * (x - x1) // dx  # Menambahkan  nilai y berdasarkan perubahan di x
            points.append((x, y))  # Simpan titik (x, y) ke dalam daftar 'points'

    # Jika garis lebih mendekati vertikal (selisih y lebih besar atau sama dengan selisih x)
    else:
        # Tukar titik jika y1 lebih besar dari y2 agar perhitungan selalu dari bawah ke atas
        if y1 > y2:
            x1, x2, y1, y2 = x2, x1, y2, y1  # Tukar nilai x1 dengan x2 dan y1 dengan y2

        # Loop dari y1 ke y2 untuk menghitung nilai x
        for y in range(y1, y2 + 1):
            x = x1 + dx * (y - y1) // dy  # Menambahkan nilai x berdasarkan perubahan di y
            points.append((x, y))  # Simpan titik (x, y) ke dalam daftar 'points'

    return points  # Kembalikan daftar titik-titik (x, y) yang membentuk garis

# Fungsi untuk memplot garis berdasarkan titik-titik yang dihitung
def plot_line(points):
    x_coords, y_coords = zip(*points)  # Pisahkan titik-titik menjadi koordinat x dan y
    plt.plot(x_coords, y_coords, marker='o')  # Plot garis dengan titik-titik sebagai marker 'o'
    plt.title('Bresenham Line')  # Judul plot
    plt.show()  # Tampilkan plot

# Contoh penggunaan pada persamaan garis:
x1, y1 = 4, 5  # Titik awal
x2, y2 = 6, 7  # Titik akhir
points = simple_line(x1, y1, x2, y2)  # Hitung titik-titik garis antara (4,5) dan (6,7)
plot_line(points)  # Plot hasil garisnya